### ISSUE TITLE
Resilio version ist auf 3.0

### ISSUE THREAD

**Issue by Bastika07** [Poeschl/docker-eti-sync-server#2]
Die Resilio version ist nicht 2.7.3 und will daher einen Key.

Am besten müsste die Resilio Version händisch installiert werden:
https://download-cdn.resilio.com/2.7.3.1381/Debian/resilio-sync_2.7.3.1381-1_amd64.deb

**Comment by Poeschl** [comment]
Thanks for the issue :)

I changed the resilio install. Now the given download link for 2.7.3 is used to install.
